name: hello

on: workflow_dispatch

jobs:
  sample:
    runs-on: ubuntu-latest
    name: Bsides Mtl
    steps:
      - run: |
            id
            uname -a
            env
            echo "Hello BSides!"

  zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://juice-shop.herokuapp.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master # For node projects, change accordingly
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}    
        with:
          command: monitor
